micronaut:
  application:
    name: dnaadmin
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger/org/sggw
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/org/sggw/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/org/sggw/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/org/sggw/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
flyway:
  datasources:
    default:
      enabled: true
